import Head from "next/head";
import { URL } from "node:url";

export const getServerSideProps = async (context) => {
    return {
        props: {
            host: new URL(
                "/api/redirect",
                `http://${context.req.headers.host}`
            ).toString(),
        },
    };
};

export default function Home({ host }) {
    return (
        <div>
            <Head>
                <title>Link Forwarder</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Link forwarder</h1>
                <h2>How to use</h2>
                <p>
                    Just append a search param with key `to` to{" "}
                    {`${host}?to<YOUR_URL>`}
                </p>
            </main>
        </div>
    );
}
